{
 "title": "Productivity System",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  { "title": "Personal", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "No. of  cards Done this week",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "personal_board_done_count - (personal_board_done_count offset 1w)"
    }
   ]
  },
  {
   "title": "No. of cards added this week",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(personal_board_inbox_count + personal_board_waiting_count + personal_board_this_week_count + personal_board_tomorrow_count + personal_board_today_count + personal_board_done_count)\n- \n(personal_board_inbox_count offset 1w + personal_board_waiting_count offset 1w + personal_board_this_week_count offset 1w + personal_board_tomorrow_count  offset 1w + personal_board_today_count offset 1w + personal_board_done_count offset 1w)"
    }
   ]
  },
  {
   "title": "This week",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "personal_board_this_week_count" }
   ]
  },
  {
   "title": "Today",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 15, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "personal_board_today_count" }
   ]
  },
  { "title": "Work", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "No. of  cards Done this week",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "work_board_done_count - (work_board_done_count offset 1w)"
    }
   ]
  },
  {
   "title": "No. of cards added this week",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(work_board_inbox_count + work_board_waiting_count + work_board_this_week_count + work_board_tomorrow_count + work_board_today_count + work_board_done_count)\n- \n(work_board_inbox_count offset 1w + work_board_waiting_count offset 1w + work_board_this_week_count offset 1w + work_board_tomorrow_count  offset 1w + work_board_today_count offset 1w + work_board_done_count offset 1w)"
    }
   ]
  },
  {
   "title": "This week",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "work_board_this_week_count" }
   ]
  },
  {
   "title": "Today",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 15, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "work_board_today_count" }
   ]
  }
 ]
}