version: "3.6"

services:
  personal-trello-exporter:
    build: 
      context: .
    image: personal-trello-exporter:latest 
    env_file: .env
    networks:
      - internal_network
    
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    networks:
      - internal_network
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports: 
      - 80:3000
    networks:
      - internal_network
    volumes:
      - grafana_storage:/var/lib/grafana
    env_file: .env

networks:
  internal_network:

volumes:
  grafana_storage: